db:
  username: postgres
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    timeout: 10 

#spring.profiles.active:qa
#spring.profiles.active:prod



logging:
  level:
    root: INFO
    com.study.spring.database.pool.ConnectionPool: INFO
#    com.study.spring.database.pool: INFO   -> for some package
#for logging in file here
#  file:
#    name: test.log

#darasourse config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate